In [1]:
#Array

import numpy as np
# Create an aray from a lít

a =  [1, 2, 3, 4 , 5]
b = np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
a = [1, 'hello', 3.14]
b = np.array(a)
print(b)

['1' 'hello' '3.14']


In [23]:
# Hàm Linespace: tạo mảng với các giá trị cách đều nhau
# Syntax: np.linspace(start, stop, num=50, endpoint=True, retstep= False, dtype=None)
a = np.linspace(0, 10, 6, dtype=int)
print(a)
a = np.linspace(0, 10, 5, endpoint=False, dtype=int)
print(a)
a, distance = np.linspace(0, 5, 15, retstep=True, endpoint=False)
print(a)
print(distance)

[ 0  2  4  6  8 10]
[0 2 4 6 8]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667]
0.3333333333333333


In [8]:
# arange function: create arrays with evenly spaced values
# syntax: np.arange(start, stop, step, dtype=None)
a = np.arange(0, 10, 2)
print(a)
b = np.arange(0, 15, 0.5)
print(b)

[0 2 4 6 8]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5]


In [12]:
# logspace function: create arrays with evenly spaced values on a log scale
# syntax: np.logspace(start, stop, num=50, endpoint=true, base=10.0, dtype=None)
a = np.logspace(0, 3, 4, base=10, dtype=int)
print(a)
a = np.logspace(1, 10, 10, base=2, dtype=int)
print(a)
a = np.logspace(1, 9, 5, base=3, dtype=int)
print(a)

[   1   10  100 1000]
[   2    4    8   16   32   64  128  256  512 1024]
[    3    27   243  2187 19683]


In [21]:
a = np.zeros(5, dtype=int)
print(a)
a = np.ones(10, dtype=int)
print(a)

[0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


In [24]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[0 0 1 2 5]
[1 2 0 0 0]
[ 1 16 27 16  5]


In [25]:
a = np.array([1,2,3,4,5])
b = a + 10
print(b)
print(a -10)
print(a * 10)
print(a / 10)
print(a // 10)
print(a % 10)
print(a ** 10)

[11 12 13 14 15]
[-9 -8 -7 -6 -5]
[10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]
[0 0 0 0 0]
[1 2 3 4 5]
[      1    1024   59049 1048576 9765625]


In [27]:
# create array of 20 random integers from 10 to 99
a = np.random.randint(10, 100, 20)
print(a)

[91 94 87 27 53 24 13 63 18 70 73 79 65 41 71 66 35 47 43 85]


In [29]:
b = a % 2 == 0
print(b)

[False  True False False False  True False False  True  True False False
 False False False  True False False False False]


In [34]:
#boolean indexing
evens = a[b]
print(evens)
odds = a[a % 2 == 1]
print(odds)

[94 24 18 70 66]
[91 87 27 53 13 63 73 79 65 41 71 35 47 43 85]


In [37]:
# create 20 random numbers from -99 to 99
#find positive numbers
#find negative numbers
a = np.random.randint(-99, 100, 20)
print(a)
positives = a[a > 0]
negatvies = a[a < 0]
print(positives, negatvies, sep='\n')

[-16   4  79 -45  84  -6  91  52  73  92  45 -55  32 -53  34  33 -46 -85
  99 -88]
[ 4 79 84 91 52 73 92 45 32 34 33 99]
[-16 -45  -6 -55 -53 -46 -85 -88]


In [47]:
a = np.linspace(0, 20, 10, endpoint=False, dtype=int)
print(a)
a = np.arange(0, 20, 2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [64]:
a = np.random.randint(0, 100, 20)
print(a)
evens = a[a % 2 == 0]
odds = a[a % 2 == 1]
evens = np.array(sorted(evens))
odds = np.array(sorted(odds))
print(evens, odds, sep='\n')
a = np.concatenate((evens, odds))
print(a)

[ 6 79 10 51 46 54 16 79 41 39 76 57 10 83 93 53 60 76 27 40]
[ 6 10 10 16 40 46 54 60 76 76]
[27 39 41 51 53 57 79 79 83 93]
[ 6 10 10 16 40 46 54 60 76 76 27 39 41 51 53 57 79 79 83 93]


In [1]:
import numpy as np
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.])
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2])
v = (y[1:]-y[:-1]) / (t[1:] - t[:-1])
print(v)


[ 2.65306122  7.25490196 11.8        13.79310345 20.85106383 17.38461538]


In [7]:
a = np.random.randint(-90, 100, 20)
print(a)
positives = a[a > 0]
print(positives)
#convert negatives to 0
# a[a < 0] = 0
# print(a)
#convert negatives to their absolute value
a[a < 0] *= -1
print(a)

[-68 -31 -32  93  73 -37 -67   1  -5 -62  29 -15  25  94  97  96 -81  47
 -27  34]
[93 73  1 29 25 94 97 96 47 34]
[68 31 32 93 73 37 67  1  5 62 29 15 25 94 97 96 81 47 27 34]


In [18]:
import numpy as np
name = np.array(['asd', 'qqqqq', '', 'bmbmbsssss', ''])
age = np.array([13, -150, -50, 200, 20])
#Convert empty name to "John Doe"
empty = name[name == ''] = 'John Doe'
print(name)
#convert age less than 0 to 0
negatives = age[age < 0]
print(negatives)
age[age < 0] = 0
print(age)
#convert age greater than 150 to 150
positives = age[age > 150] = 150
print(age)
#find max min of ages
print('max of age: ', max(age))
print('min of age: ', min(age))
#find longest, shortest name
print('Longest name: ', max(name, key=len))
print('shortest name:', min(name, key=len))

['asd' 'qqqqq' 'John Doe' 'bmbmbsssss' 'John Doe']
[-150  -50]
[ 13   0   0 200  20]
[ 13   0   0 150  20]
max of age:  150
min of age:  0
Longest name:  bmbmbsssss
shortest name: asd


In [72]:
import numpy as np
a = np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
            [13, 14, 15, 16]])
# print(a[1,2])
print(a[:,3])
# print(a[-3:])
# print(a[:3])
# print(a[:,-3:])
print(a[:,:3])
print(len(a))

[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
4


In [4]:
import numpy as np
b = np.array([[np.random.randint(10, 100, 5)],
            [np.random.randint(10, 100, 5)],    
            [np.random.randint(10, 100, 5)],
            [np.random.randint(10, 100, 5)],
            [np.random.randint(10, 100, 5)]])
print(b)
print('---------')
print(b[2:])
print('--------')
print(b[0:3, 1:4])

[[[85 42 57 24 14]]

 [[56 29 49 91 69]]

 [[93 68 65 77 23]]

 [[42 10 24 74 72]]

 [[98 49 85 37 63]]]
---------
[[[93 68 65 77 23]]

 [[42 10 24 74 72]]

 [[98 49 85 37 63]]]
--------
[]


In [45]:
ones = np.ones((5, 5), dtype=int)
print(ones)

zeros = np.zeros((5, 5), dtype=int)
print(zeros)

nine = ones * 9
print(nine)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [46]:
ones[1] = 0
print(ones)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [70]:
# a) Create an 8 × 8 array with ones on all the edges and zeros everywhere else.
ones = np.ones((8, 8), dtype=int)
ones[1:7, 1:7] = 0
print(ones)
print('---------')
# b) Create an 8 × 8 array of integers with a checkerboard pattern of ones and zeros.
checkboard = np.zeros((8, 8), dtype=int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)
# c) Create an 8 x 8 array of random integers (0, 99), make all the numbers not divisible by 3 negative. 
a = np.random.randint(10, 100, (8, 8))
print('Random: \n',a)
a[a % 3 != 0] *= -1
print('C: \n',a)
# d) Split the matrix above into 4 submatrices 4x4
q1 = a[:4, :4]
print(np.size(q1))
print(np.shape(q1))
# e) Find the size, shape, mean, and standard deviation of the matrices you created in part d
a2d = np.array([[1, 2, 3, 4]])
b1d = np.array([1, 2, 3, 4])
print(a2d, np.shape(a2d))
print(b1d, np.shape(b1d))

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
---------
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
Random: 
 [[94 15 53 25 93 59 19 79]
 [12 41 57 74 37 75 26 37]
 [39 85 58 74 20 92 65 25]
 [99 76 68 34 97 20 43 83]
 [85 96 27 13 18 58 21 30]
 [39 14 26 26 89 94 10 47]
 [14 66 42 91 86 79 84 39]
 [14 49 30 15 35 41 46 82]]
C: 
 [[-94  15 -53 -25  93 -59 -19 -79]
 [ 12 -41  57 -74 -37  75 -26 -37]
 [ 39 -85 -58 -74 -20 -92 -65 -25]
 [ 99 -76 -68 -34 -97 -20 -43 -83]
 [-85  96  27 -13  18 -58  21  30]
 [ 39 -14 -26 -26 -89 -94 -10 -47]
 [-14  66  42 -91 -86 -79  84  39]
 [-14 -49  30  15 -35 -41 -46 -82]]
16
(4, 4)
[[1 2 3 4]] (1, 4)
[1 2 3 4] (4,)


In [13]:
import numpy as np
ones = np.ones((10, 10), dtype=int)
print(ones)
print('-------------------------------------')
checkboard = np.zeros((10, 10), dtype=int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)
print('----------------------')
print(checkboard[::2])
# print(checkboard[::2] + checkboard[])
print(checkboard[::2, ::2] + 1)


[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
-------------------------------------
[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]
----------------------
[[1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1 0]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
