In [1]:
def my_sort(items, compare=lambda a, b : a > b):
    n = len(items)
    for i in range(n):
        for j in range(n-1):
            if compare(items[j], items[j+1]):
                items[j], items[j+1] = items[j+1], items[j]

In [3]:
import numpy as np
numbers = np.random.randint(0, 100, 10)
print(numbers)
my_sort(numbers)
print(numbers)
my_sort(numbers, lambda a, b : a < b)
print(numbers)
my_sort(numbers, lambda a, b : a % 10 > b % 10)
print(numbers)

[94 93 21  5 86 74 24 58 86  6]
[ 5  6 21 24 58 74 86 86 93 94]
[94 93 86 86 74 58 24 21  6  5]
[21 93 94 74 24  5 86 86  6 58]


In [9]:
numbers = np.random.randint(-99, 100, 10)
print(numbers)
# sort numbers ascending by absolute value
my_sort(numbers, lambda a, b : abs(a) > abs(b))
print(numbers)
# sort numbers descending by absolute value
my_sort(numbers, lambda a, b : abs(a) < abs(b))
print(numbers)
# sort numbers ascending by the sum of the digits
my_sort(numbers, lambda a, b: abs(a) % 10 + abs(a) // 10 > abs(b) % 10 + abs(b) // 10)
print(numbers)
# sort numbers descending by absolute value
my_sort(numbers, lambda a, b: abs(a) % 10 + abs(a) // 10 < abs(b) % 10 + abs(b) // 10)
print(numbers)

[ 88 -31 -99  66  71   6 -93  79  11  41]
[  6  11 -31  41  66  71  79  88 -93 -99]
[-99 -93  88  79  71  66  41 -31  11   6]
[ 11 -31  41   6  71 -93  66  88  79 -99]
[-99  88  79 -93  66  71   6  41 -31  11]


In [18]:
# Write a function to find the most element in a a collection of elements
def most_superior(items, compare=lambda a, b : a > b):
    n = len(items)
    most = items[0]
    for i in range(n):
        if compare(items[i], most):
            most = items[i]
    return most

In [21]:
print(numbers)
a = most_superior(numbers) # max
print(a)
b = most_superior(numbers, lambda a, b : a < b) # min
print(b)
# find the number which is closet to 0
m = most_superior(numbers, lambda a, b : abs(a) < abs(b))
print(m)
# find the number which is closet to 50
m = most_superior(numbers, lambda a, b : abs(a - 50) < abs(b - 50))
print(m)

[-99  88  79 -93  66  71   6  41 -31  11]
88
-99
6
41


In [ ]:
# Filter function syntax: filter function

In [22]:
numbers = np.random.randint(0, 100, 20)
print(numbers)
# filter even number
evens = list(filter(lambda x: x % 2 == 0, numbers))
print(evens)
# filter odds number
odds = list(filter(lambda x: x % 2 == 1, numbers))
print(odds)

[82 92 50  6 89 64 79 82 20 35 49 33 30 51 40 12  7 81 27 27]
[82, 92, 50, 6, 64, 82, 20, 30, 40, 12]
[89, 79, 35, 49, 33, 51, 7, 81, 27, 27]


In [23]:
s = 0
for n in numbers:
    if n % 2 == 0:
        s += n
print(s)

478


In [24]:
evens = [n for n in numbers if n % 2 == 0]
print(sum(evens))

478


In [25]:
evens = filter(lambda x: x % 2 == 0, numbers)
print(sum(evens))

478


In [29]:
numbers = np.random.randint(-99, 100, 10)
print(numbers)
# find max of negative numbers
negative = filter(lambda x: x < 0, numbers)
print(max(negative))
# find min of positive numbers
positive = filter(lambda x: x > 0, numbers)
print(min(positive))

[ 24  39  91 -75  64 -51 -90 -81  75 -25]
-25
24


In [36]:
students = {'John': (7.5, 90), 'Mary': (8.5, 95), 'Bob': (6.0, 80), 
            'Alice': (5.5, 100), 'Peter': (8.0, 70), 'Jane': (9.0, 30)}
# Best student is the one with the GPA > 7.0 and highest activity score
candidates = filter(lambda x: x[1][0] > 7.0 and x[1][1] > 80, students.items())
best_student = max(candidates, key=lambda x: x[1][1])
print(f'best student is: {best_student[0]}')

#Find the most nerd student (activity score < 50 and highest GPA)
candidates = filter(lambda x: x[1][0] > 8.0 and x[1][1] < 50, students.items())
nerd_students = max(candidates, key=lambda x: x[1][0])
print(f'nerd student is: {nerd_students[0]}')

best student is: Mary
nerd student is: Jane


In [37]:
# Map function syntax: mapFunction, iterable
# convert each item in iterable to a new item using funciton
numbers = np.random.randint(-99, 100, 10)
print(numbers)
# double each number
double_numbers = list(map(lambda x: x * 2, numbers))
print(double_numbers)
# convert negative number to positive
positive_numbers = list(map(lambda x: x if x > 0 else -x, numbers))
print(positive_numbers)

[ 27  43  78   2  -2  22  -3 -77 -69   1]
[54, 86, 156, 4, -4, 44, -6, -154, -138, 2]
[27, 43, 78, 2, 2, 22, 3, 77, 69, 1]


In [39]:
names = ['John', 'Mary', 'Alice', 'Jane', '', 'jane']
# convert empty names = default name (e.g 'Unknown)
empty_name = list(map(lambda x: x if x != '' else 'Unknown', names))
print(empty_name)

['John', 'Mary', 'Alice', 'Jane', 'Unknown', 'jane']
